# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zip',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip', to='rawApi.City'),
        ),
        migrations.AlterField(
            model_name='zip',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip', to='rawApi.Country'),
        ),
    ]
